name: Feature Request
description: No, i won't add 6K/etc to the engine or winning icons, stop asking for it.
labels: [enhancement]

body:
  - type: textarea
    id: feature
    attributes:
      label: "What feature do you want to get added on the **base** engine?"
    validations:
      required: true
      
body:
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

body:
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - Stage Editor, 6K+ support, and winning icons.
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
